@startuml
object Player {
  name = <<chosen by user>>
  OwnedPokemons = [<<chosen on starter>>]
  MoneyAmount;
  CurrentCity;
}

object Pokemon {
  name = <<Pokemon name>>
  element = <<Pokemon element>>
  hp = <<hp value>>
  attack = <<attack value>>
}


object WildPokemon {
    name = <<WildPokemon name>>
    element = <<WildPokemon element>>
    hp = <<hp value>>
    attack = <<attack value>>
}

object StorePokemon{
    name = <<StorePokemon name>>
    element = <<StorePokemon element>>
    hp = <<hp value>>
    attack = <<attack value>>
    price = <<price value>>
}

WildPokemon --|> Pokemon
StorePokemon --|> Pokemon



Player --> Pokemon
@enduml